### ISSUE TITLE
Remove the description on the Glow Ink Torch

### ISSUE THREAD

**Issue by Progical** [Phoupraw/TorchesInWater#1]
The description seems unnecessary and takes up far too much space when hovering over the Glow Ink Torch.
![Screenshot 2024-03-24 163902](https://github.com/Phoupraw/TorchesInWater/assets/32730946/1428e680-9c84-4451-82bc-a8366764bf59)

**Comment by Phoupraw** [comment]
I just wrote it in Chinese first and simply translated it into English. It isn't that long in Chinese though. I will move it to config screen in the next version.

**Comment by Phoupraw** [comment]
Fixed in [0.2.1](https://modrinth.com/mod/torches-in-water/version/0.2.1).
